VideoStore/Models/ErrorViewModel.cs
namespace VideoStore.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

VideoStore/Models/movies.cs
namespace VideoStore.Models
{
    public class movies
    {
        public int Id { get; set; }
        public string title { get; set; }
        public string type { get; set; }
        public string   source { get; set; }
        public string  thumbnail { get; set; }
        public string  link { get; set; }
        public string duration { get; set; }
        public string synopsis { get; set; }
    }
}

VideoStore/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using VideoStore.Models;

namespace VideoStore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

VideoStore/Controllers/moviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VideoStore.Data;
using VideoStore.Models;

namespace VideoStore.Controllers
{
    public class moviesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public moviesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: movies
        [Authorize]
        public async Task<IActionResult> Index()
        {
              return _context.movies != null ? 
                          View(await _context.movies.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.movies'  is null.");
        }

        // GET: movies/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.movies == null)
            {
                return NotFound();
            }

            var movies = await _context.movies
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movies == null)
            {
                return NotFound();
            }

            return View(movies);
        }

        // GET: movies/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: movies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Id,title,type,source,thumbnail,link,duration,synopsis")] movies movies)
        {
            if (ModelState.IsValid)
            {
                _context.Add(movies);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(movies);
        }

        // GET: movies/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.movies == null)
            {
                return NotFound();
            }

            var movies = await _context.movies.FindAsync(id);
            if (movies == null)
            {
                return NotFound();
            }
            return View(movies);
        }

        // POST: movies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("Id,title,type,source,thumbnail,link,duration,synopsis")] movies movies)
        {
            if (id != movies.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(movies);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!moviesExists(movies.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(movies);
        }

        // GET: movies/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.movies == null)
            {
                return NotFound();
            }

            var movies = await _context.movies
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movies == null)
            {
                return NotFound();
            }

            return View(movies);
        }

        // POST: movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.movies == null)
            {
                return Problem("Entity set 'ApplicationDbContext.movies'  is null.");
            }
            var movies = await _context.movies.FindAsync(id);
            if (movies != null)
            {
                _context.movies.Remove(movies);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool moviesExists(int id)
        {
          return (_context.movies?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

VideoStore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
    <div class="hero">
        <div class="left">
            <h2>Movies On One Click</h2>
            <p>Don't fiddle too much, select movies and watch immediately. No gimmicks! No redirection to another fishy website. Just click and watch</p>
            <a class="nav-link text-dark" asp-area="" asp-controller="movies" asp-action="Index"><button>Explore Movies</button></a>
        </div>
        <div class="right">
            <img src="~/images/d.png" />
        </div>
    </div>

VideoStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VideoStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VideoStore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VideoStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy"></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="movies" asp-action="Index"></a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

VideoStore/Views/movies/Create.cshtml
@model VideoStore.Models.movies

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>movies</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="title" class="control-label"></label>
                <input asp-for="title" class="form-control" />
                <span asp-validation-for="title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="type" class="control-label"></label>
                <input asp-for="type" class="form-control" />
                <span asp-validation-for="type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="source" class="control-label"></label>
                <input asp-for="source" class="form-control" />
                <span asp-validation-for="source" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="thumbnail" class="control-label"></label>
                <input asp-for="thumbnail" class="form-control"  type="file"/>
                <span asp-validation-for="thumbnail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="link" class="control-label"></label>
                <input asp-for="link" class="form-control" />
                <span asp-validation-for="link" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="duration" class="control-label"></label>
                <input asp-for="duration" class="form-control" />
                <span asp-validation-for="duration" class="text-danger"></span>
            </div> 
            <div class="form-group">
                <label asp-for="synopsis" class="control-label"></label>
                <input asp-for="synopsis" class="form-control" />
                <span asp-validation-for="synopsis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

VideoStore/Views/movies/Delete.cshtml
@model VideoStore.Models.movies

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>movies</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.source)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.source)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.thumbnail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.thumbnail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.link)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.link)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.duration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.duration)
        </dd> 
         <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.synopsis)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.synopsis)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

VideoStore/Views/movies/Details.cshtml
@model VideoStore.Models.movies;

@{
    ViewData["Title"] = "Details";
}
<section class="detail">
    <div class="left">
        <img src="~/images/@Html.DisplayFor(model => model.thumbnail)" />
    </div>
    <div class="right">
        <h3>@Html.DisplayFor(model => model.title)</h3>
        <div class="flexme">
            <p>@Html.DisplayFor(model => model.source)</p>
            <p>@Html.DisplayFor(model => model.type)</p>
            <p>@Html.DisplayFor(model => model.duration)</p>
        </div>
        <p>@Html.DisplayFor(model => model.synopsis)</p>
        <div class="bottomflex">
            <a href="@Html.DisplayFor(model => model.link)" target="_blank"><button>Watch Now</button></a>
            <a asp-action="Edit" asp-route-id="@Model?.Id"><button>Edit</button></a> 
            <a asp-action="Index"><button>Back to List</button></a>
    
</div>
    </div>
</section>

VideoStore/Views/movies/Edit.cshtml
@model VideoStore.Models.movies

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>movies</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="title" class="control-label"></label>
                <input asp-for="title" class="form-control" />
                <span asp-validation-for="title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="type" class="control-label"></label>
                <input asp-for="type" class="form-control" />
                <span asp-validation-for="type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="source" class="control-label"></label>
                <input asp-for="source" class="form-control" />
                <span asp-validation-for="source" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="thumbnail" class="control-label"></label>
                <input asp-for="thumbnail" class="form-control" type="file"/>
                <span asp-validation-for="thumbnail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="link" class="control-label"></label>
                <input asp-for="link" class="form-control" />
                <span asp-validation-for="link" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="duration" class="control-label"></label>
                <input asp-for="duration" class="form-control" />
                <span asp-validation-for="duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="synopsis" class="control-label"></label>
                <input asp-for="synopsis" class="form-control" />
                <span asp-validation-for="synopsis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

VideoStore/Views/movies/Index.cshtml
@model IEnumerable<VideoStore.Models.movies>

@{
    ViewData["Title"] = "Index";
}

<section class="topHeader">
    <div>
        <h5>Our Movies</h5>
        <p>Explore or series of Movies</p>
    </div>
   
    <p class="createnew">
    <a asp-action="Create"><button>Create New</button></a>
</p>
</section>
<section class="movieContainer">
@foreach (var item in Model)
{
    <a asp-action="Details" asp-route-id="@item.Id">


    <div class="eachMovie">
        <img src="~/images/@Html.DisplayFor(modelItem => item.thumbnail)" />
        <h6> @Html.DisplayFor(modelItem => item.title)</h6>
        <div class="bottom">
            <p>@Html.DisplayFor(modelItem => item.type)</p>
            <p>@Html.DisplayFor(modelItem => item.source)</p>
            <p> @Html.DisplayFor(modelItem => item.duration)</p>
        </div>
    </div>
    </a>

}

</section>
<p class="addnew">
    <a asp-action="Create"><button >Create New</button></a>
</p>











@*

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.source)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.thumbnail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.link)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.duration)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
{
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.source)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.thumbnail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.link)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.duration)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
*@